{% set name = "types-redis" %}
{% set version = "4.1.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-redis-{{ version }}.tar.gz
  sha256: b4da90107cd7239fc0cbcbff4c04c4e6f549935baa273a33fd456bfc14c3e8c5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/redis-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for redis
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
